services:
  dertutor-pg:
    image: postgres
    container_name: dertutor-pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./data/dertutor/postgres-db:/var/lib/postgresql/data
    networks:
      - network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin/
  #   networks:
  #     - network

  dertutor-api:
    container_name: dertutor-api
    build:
      context: ./dertutor-api
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      dertutor-pg:
        condition: service_healthy
    links:
      - dertutor-pg
    environment:
      - UVICORN_RELOAD=true
      - POSTGRES_DB_URL=postgresql+asyncpg://postgres:postgres@dertutor-pg:5432/postgres
      - CONNECT_EN_RU_DB=false
      - CONNECT_EN_PRON_DB=false
      - CONNECT_DE_PRON_DB=false
    volumes:
      - ./dertutor-api:/app
      - ./data/dertutor:/app/data
    ports:
      - 3002:80
    tty: true
    networks:
      - network


  dertutor-web-client:
    container_name: dertutor-web-client
    build:
      context: ./dertutor-web
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      - VITE_DERTUTOR_API_URL=http://localhost:3002/api
    depends_on:
      - dertutor-api
    volumes:
      - ./dertutor-web/src:/app/src
    ports:
      - 3003:3000
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data: